version: "3.7"

services:
  client:
    container_name: url-uuid-client
    build:
      context: .
      dockerfile: client.Dockerfile

    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"

  server:
    container_name: url-uuid-server
    build:
      context: .
      dockerfile: server.Dockerfile

    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - "mongo"
    ports:
      - "3100:3100"
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: "mongo"
    ports:
      - "27018:27017"
