version: "3.7"

services:
  my-app:
    container_name: url-uuid-app
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - "mongo"
    ports:
      - "8081:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
